# Version specific
FROM ubuntu:24.04

# -- container ID
ARG OPENAPX_CONTAINERID="unknown"

# -- add license file to root directory
COPY LICENSE /LICENSE-baseline-os



# -- binary libraries
#    note: difference in repo locations
#    note: include OS updates

COPY libs-ubuntu /opt/openapx/config/baseline-os/
COPY --chmod=755 scripts/baseline-os/bin-libs.sh scripts/baseline-os/container-id.sh /opt/openapx/utilities/

RUN /opt/openapx/utilities/container-id.sh && \
    /opt/openapx/utilities/bin-libs.sh --with-updates /opt/openapx/config/baseline-os/libs-ubuntu


