# Version specific
FROM rockylinux:9.3


# -- add license file to root directory
COPY LICENSE /LICENSE-baseline-os



# -- binary libraries
#    note: difference in repo locations
#    note: include OS updates

COPY libs-rockylinux /opt/openapx/config/baseline-os/
COPY --chmod=755 scripts/baseline-os/bin-libs.sh /opt/openapx/utilities/

#    note: need extended packages for linux
RUN dnf install --assumeyes epel-release && \
    /opt/openapx/utilities/bin-libs.sh --with-updates /opt/openapx/config/baseline-os/libs-rockylinux


